### ISSUE TITLE
Request to join the team

### ISSUE THREAD

**Issue by Aissaoui-Ahmed** [nodejs/nodejs-ar#5]
Hello everyone.

I've worked on translation with @celyes and @3imed-jaberi on website but our problem in organizational matters like the glossary and duplicate translation ... etc.
i would like to ask you about the method in which i'll be a member in the team @nodejs/node-ar.

**Comment by celyes** [comment]
Add me too.

**Comment by 3imed-jaberi** [comment]
Add me too ..

**Comment by Trott** [comment]
Since all of you have commits into the website already, I went ahead and added you to the team. I suspect the main purpose of the team at this point is to be pinged on Arabic-language contributions. This repository itself is not active, and everything that once would have gone here now goes through the main nodejs.org repository. For docs, I think we use CrowdIn, which I don't *think* touches this repository. It's likely we'll just archive this repository, but I'm going through issues and PRs now to get a feel for stuff.

**Comment by 3imed-jaberi** [comment]
Please @Trott  , I ask you to leave us some time to do a rearrangement of this repo and then archiving it .. 
Personally, I think it is a shame for the Arab community to leave this repo in this way.

Thank you so much again bro ❤️ ..

**Comment by Trott** [comment]
> Please @Trott , I ask you to leave us some time to do a rearrangement of this repo and then archiving it ..
> Personally, I think it is a shame for the Arab community to leave this repo in this way.
> 
> Thank you so much again bro ❤️ ..

Yup, no problem. Let me know if you change your mind and want it archived. I think it might be best to update the README to direct people to the nodejs.org repo (for website translation activity) and CrowdIn (for documentation translation activity), and then archive. But whatever the team wants to do with it is fine with me.

**Comment by atefBB** [comment]
@Trott Can you add me too?!

**Comment by Trott** [comment]
> @Trott Can you add me too?!

@atefBB You should have an invitation now. You'll need to have two-factor authentication enabled or it won't let you join the org. Send me an email (listed on my GitHub profile page) if it's not working for you.

**Comment by atefBB** [comment]
@Trott it's not working for me, I'll check the email option.
